---
# Install Git package

- name: install git - CentOS
  yum:
             pkg={{ item }}
    update_cache=yes
           state=present
  with_items:
    - git
  when: ansible_distribution == "CentOS"

- name: install git - Ubuntu
  apt:
                 pkg={{ item }}
        update_cache=yes
    cache_valid_time=3600
               state=present
  with_items:
    - git
  when: ansible_distribution == "Ubuntu"
